name: "03-EKS_Fargate"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/develop'
    uses: conover0701/gitreusableworkflow/.github/workflows/aws_tf_plan.yml@develop
    with:
      path: EKS_Fargate
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: conover0701/gitreusableworkflow/.github/workflows/aws_tf_appy.yml@develop
    with:
      path: EKS_Fargate
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Plan_Uat:
    if: github.ref == 'refs/heads/main'
    uses: conover0701/gitreusableworkflow/.github/workflows/aws_tf_plan.yml@main
    with:
      path: EKS_Fargate
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Uat:
    needs: Plan_Uat
    uses: conover0701/gitreusableworkflow/.github/workflows/aws_tf_appy.yml@main
    with:
      path: EKS_Fargate
      tf_vars_file: uat.tfvars
      gh_environment: uat
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}